spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-230-122-20.compute-1.amazonaws.com/dfqaq3q3otkpr
  username: kvtjmldgdztcet
  password: 2bbc6d7a2689962034ef5310def8f761373284ce0029b754cf4ef48142eb1c0c
  platform: postgres
  dirver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.redis:
  url: redis://:p14709f4b193beefe6ff815dd7b2cdab06e306737ee872ce56bb3c9eed69c3a0d@ec2-52-203-197-248.compute-1.amazonaws.com:9149

jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="jfsgwscs" password="PgXfz0_F3IGSwM7REUC2aH-xNXoTMjU-";
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      group-id: jfsgwscs-
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
       ack-mode: MANUAL
    producer:
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: jfsgwscs-alarm





