spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-230-122-20.compute-1.amazonaws.com/dfqaq3q3otkpr
  username: kvtjmldgdztcet
  password: 2bbc6d7a2689962034ef5310def8f761373284ce0029b754cf4ef48142eb1c0c
  platform: postgres
  dirver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.redis:
  url: redis://:p14709f4b193beefe6ff815dd7b2cdab06e306737ee872ce56bb3c9eed69c3a0d@ec2-52-203-197-248.compute-1.amazonaws.com:9149

jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

